server:
  port: 8889
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://124.220.28.218:3306/test?useUnicode=true&characterEncoding=utf-8
    username: crz
    password: crz
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
